name: Pull and Push

on:
  push:
    branches:
      - main  # Ubah ini sesuai dengan nama cabang Anda

jobs:
  pull_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositori sumber
      uses: actions/checkout@v2
      with:
        repository: nurulekawew/inventory
        ref: main # Gunakan cabang yang ingin Anda tarik

    - name: Dorong ke repositori tujuan
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Nama Anda"
        git remote add destination https://github.com/lapengo/inventory.git
        git fetch destination
        git rebase destination/main
        git push destination main
